export const PageConst = {
    login: 'LOG IN',
    logout: 'LOG OUT',
    confirmPassword: 'CONFIRM PASSWORD',
    forgotPassword: 'FORGOT PASSWORD',
    register: 'REGISTER',
    resetPassword: 'RESET PASSWORD',
    verifyEmail: 'VERIFY EMAIL',
    aboutUs: 'ABOUT US',
    contact: 'CONTACT',
    dashboard: 'DASHBOARD',
    home: 'HOME',
    privacyPolicy: 'PRIVACY POLICY',
    reference: 'REFERENCE',
    rules: 'DATABASE RULES',
    book: {
        create: '書籍追加',
        edit: '書籍編集',
        manage: '書籍管理',
        editLibrary: '書籍-叢書/雑誌',
        editPublisher: '書籍-出版社',
        editPerson: '書籍-人物',
        editSite: '書籍-サイト',
    },
    content: {
        create: '収録追加',
        edit: '収録編集',
        manage: '収録管理',
        editPerson: '収録-人物',
        editWriting: '収録-作品',
    },
    edition: {
        create: '版追加',
        edit: '版編集',
        manage: '版管理',
        editPerson: '版-人物',
    },
    library: {
        create: '叢書/雑誌追加',
        edit: '叢書/雑誌編集',
        manage: '叢書/雑誌管理',
        editPublisher: '叢書-出版社',
        editSite: '叢書-サイト',
    },
    person: {
        create: '人物追加',
        edit: '人物編集',
        manage: '人物管理',
        editAlias: '人物-人物',
        editSite: '人物-サイト',
    },
    publisher: {
        create: '出版社追加',
        edit: '出版社編集',
        manage: '出版社管理',
        editAlias: '出版社-出版社',
        editSite: '出版社-サイト',
    },
    series: {
        create: 'シリーズ追加',
        edit: 'シリーズ編集',
        manage: 'シリーズ管理',
        editPerson: 'シリーズ-人物',
        editSite: 'シリーズ-サイト',
    },
    site: {
        create: 'サイト追加',
        edit: 'サイト編集',
        manage: 'サイト管理',
    },
    writing: {
        create: '作品追加',
        edit: '作品編集',
        manage: '作品管理',
        editAlias: '作品-作品',
        editPerson: '作品-人物',
        editSeries: '作品-シリーズ',
        editSite: '作品-サイト',
    },
};
